server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cloud?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
     # defaultZone: http://localhost:7001/eureka
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.atguigu.springcloud.entities
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/*.xml
    # 加载全局的配置文件
    #configLocation: classpath:mybatis/mybatis-config.xml
