server:
  port: 9527 #服务注册中心端口号

eureka:
  instance:
    hostname: cloud-gateway-service #服务注册中心IP地址
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: false #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
     # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机版
     defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1 #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/query/** #断言：路径相匹配的进行路由


        - id: payment_routh2 #路由的id，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:8001 #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言：路径相匹配的进行路由