server:
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      host: 192.168.3.111
      port: 8500
      enabled: true
      instance-id: ${spring.application.name}:${spring.cloud.consul.port}:${random.value}
      discovery:
        hostname: 192.168.3.111
        service-name: ${spring.application.name}
        register-health-check: false #健康检查设置false，不然报红叉
        #配置服务注册
        register: true
        #服务停止时取消注册，http://www.imooc.com/article/286883?block_id=tuijian_wz
        deregister: true
        #表示注册时使用ip而不是hostname
        prefer-ip-address: true
        #健康检查失败多长时间取消注册
        health-check-critical-timeout: 30s
